// Zeron mobile — Expo CNG config (docs/COMPATIBILITY.md "Native project
// strategy"). All native customizations live here as plugins; ios/ is
// generated by `npx expo prebuild` and not committed.
import type { ExpoConfig, ConfigContext } from 'expo/config';

const edgeUrl = process.env.ZERON_EDGE_URL ?? 'https://edge.zeron.sh';
const edgeHost = new URL(edgeUrl).host;

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'ZRemote',
  slug: 'zeron-mobile',
  version: '0.1.0',
  orientation: 'default',
  scheme: 'zeron',
  platforms: ['ios'],
  userInterfaceStyle: 'automatic',
  icon: './assets/brand/icon-1024.png',
  ios: {
    // NOT sh.zeron.ios — that identifier belongs to Zeron's SwiftUI app.
    bundleIdentifier: process.env.ZERON_IOS_BUNDLE_ID ?? 'no.hideout.zremote',
    buildNumber: process.env.IOS_BUILD_NUMBER ?? '1',
    // TestFlight pipeline only — never hardcode a team id in a public repo.
    ...(process.env.APPLE_TEAM_ID !== undefined
      ? { appleTeamId: process.env.APPLE_TEAM_ID }
      : {}),
    // expo-widgets reads this (not Podfile.properties.json) for the
    // widgets extension target; keep it in sync with build-properties.
    deploymentTarget: '17.0',
    supportsTablet: true,
    requireFullScreen: false,
    associatedDomains: [`applinks:${edgeHost}`],
    entitlements: {
      'aps-environment': 'development',
    },
    infoPlist: {
      NSMicrophoneUsageDescription:
        'ZRemote uses the microphone to dictate prompts and commands to remote coding engines.',
      NSSpeechRecognitionUsageDescription:
        'ZRemote uses speech recognition to transcribe dictated prompts into text for remote sessions.',
      NSCameraUsageDescription:
        'ZRemote uses the camera to attach photos to messages sent to remote coding engines.',
      NSPhotoLibraryUsageDescription:
        'ZRemote accesses the photo library to attach images to messages and to choose a custom background.',
      NSSupportsLiveActivities: true,
      NSSupportsLiveActivitiesFrequentUpdates: true,
      ITSAppUsesNonExemptEncryption: false,
      // Explicitly none: the phone is a peer that renders and commands; it
      // does not run background execution modes.
      UIBackgroundModes: [],
    },
  },
  extra: {
    edgeUrl,
    workosClientId:
      process.env.ZERON_WORKOS_CLIENT_ID ?? 'client_01KWD0EAKZKD50YCQJNYSRE4BY',
    workosApiBase: 'https://api.workos.com',
    gitSha: process.env.GITHUB_SHA ?? 'dev',
  },
  plugins: [
    [
      'expo-build-properties',
      // UIKit scene lifecycle is mandatory when built with the iOS 27 SDK.
      { ios: { deploymentTarget: '17.0', enableSceneSupport: true } },
    ],
    [
      'react-native-bootsplash',
      {
        logo: './assets/brand/splash-logo.png',
        background: '#000000',
        logoWidth: 54,
        assetsOutput: './assets/bootsplash',
      },
    ],
    // Live Activities are runtime-registered — no widgets[] entries here.
    ['expo-widgets', { enablePushNotifications: true }],
    ['expo-notifications', { enableBackgroundRemoteNotifications: false }],
    './plugins/withPodfileMods',
    'expo-secure-store',
    'expo-web-browser',
  ],
});
